site_name: Unity-Powershell Documentation
repo_url: https://github.com/equelin/Unity-Powershell
site_author: Erwan Quelin
theme: readthedocs
copyright: "Unity-Powershell is licensed under the <a href='https://github.com/equelin/Unity-Powershell/blob/master/LICENSE'>MIT license</a>"
pages:
  - Home: index.md
  - Introduction:
    - Prerequisites: prerequisites.md
    - Installation: installation.md
    - Getting Started: gettingstarted.md
  - FAQ: FAQ.md